apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-management-service-config
  namespace: openfuyao-system
data:
  config.yaml: |
    marketplace-service-host: {{.Values.serverHost.marketplaceService}}
